### ISSUE TITLE
Réponse de l'API

### ISSUE THREAD

**Issue by sakkhho** [pgrimaud/horaires-ratp-api#12]
Bonjour,
Merci pour la V2

en faisant cela
http://api-ratp.pierre-grimaud.fr/v2/rers/a/stations/grande+arche+la+defense?destination=st+germain+en+laye+poissy+cergy

par moment, l'api retourne presque rien genre : 
{
    "response": {
        "informations": {
            "destination": {
                "id": "1",
                "name": "St-Germain-en-Laye Poissy-Cergy",
                "slug": "st+germain+en+laye+poissy+cergy"
            },
            "line": "A",
            "type": "rer",
            "station": {
                "id": "12",
                "name": "Grande Arche La Defense",
                "slug": "grande+arche+la+defense"
            }
        },
        "schedules": [
            {
                "destination": "St-Germain-en-Laye Poissy-Cergy",
                "message": "Service terminé ou horaires indisponibles"
            }
        ]
    },
    "_meta": {
        "version": "2",
        "date": "2016-01-03T21:58:35+01:00",
        "call": "GET /rers/a/stations/grande+arche+la+defense?destination=st+germain+en+laye+poissy+cergy"
    }
}

alors que le coup d'après, si je rafraichis j'ai bien la réponse

{
    "response": {
        "informations": {
            "destination": {
                "id": "1",
                "name": "St-Germain-en-Laye Poissy-Cergy",
                "slug": "st+germain+en+laye+poissy+cergy"
            },
            "line": "A",
            "type": "rer",
            "station": {
                "id": "12",
                "name": "Grande Arche La Defense",
                "slug": "grande+arche+la+defense"
            }
        },
        "schedules": [
            {
                "id": "UPIR",
                "destination": "Cergy-Le Haut",
                "message": "22:05 Voie 2"
            },
            {
                "id": "ZEMA",
                "destination": "St Germain en Laye",
                "message": "22:15 Voie 2"
            },
            {
                "id": "TETE",
                "destination": "Poissy",
                "message": "22:23 Voie 2"
            },
            {
                "id": "ZEMA",
                "destination": "St Germain en Laye",
                "message": "22:31 Voie 2"
            },
            {
                "id": "UPIR",
                "destination": "Cergy-Le Haut",
                "message": "22:37 Voie 2"
            },
            {
                "id": "ZEMA",
                "destination": "St Germain en Laye",
                "message": "22:44 Voie 2"
            }
        ]
    },
    "_meta": {
        "version": "2",
        "date": "2016-01-03T22:01:13+01:00",
        "call": "GET /rers/a/stations/grande+arche+la+defense?destination=st+germain+en+laye+poissy+cergy"
    }
}

y a il un problème quelque part ?

merci
sakkhho

**Comment by pgrimaud** [comment]
Hello,

Ouais j'ai vu ça, le site de la RATP n'est pas très stable pour les horaires du RER, je vais tenter de corriger ça.

**Comment by pgrimaud** [comment]
Bonsoir @sakkhho ,
Je pense que c'est corrigé. Le site de la RATP se montre trop souvent capricieux avec les horaires du RER. Je viens d'effectuer des tests et je n'ai plus de page avec comme réponse "Service terminé ou horaires indisponibles" en journée.
