### ISSUE TITLE
Erreur de documentation pour l'API traffic

### ISSUE THREAD

**Issue by mgarstecki** [pgrimaud/horaires-ratp-api#13]
La spécification de l'API traffic comporte une erreur, dans la ligne `http://api-ratp.pierre-grimaud.fr/v2/trafic/({TypeLigne}/{LigneId})` il manque un deuxième f à traf**f**ic.

**Comment by pgrimaud** [comment]
Bonjour,
Bien vu, merci. 

Corrigé
