### ISSUE TITLE
Problème Horaires métro 7

### ISSUE THREAD

**Issue by KisaW** [pgrimaud/horaires-ratp-api#14]
Bonjour,

Je souhaiterais les horaires de la ligne 7 (Métro) de la station Poissonnière à Pyramides par exemple.

Je fais donc la requête suivante : http://api-ratp.pierre-grimaud.fr/v2/metros/7/stations/poissonniere?destination=pyramides

Cette requête me return code "404" et donc le message : "Ressource not found".

Une idée ?

Merci en tout cas, super cool c'est API :+1: Félicitations !

**Comment by KisaW** [comment]
Il semblerait que cela fonctionne uniquement avec l'exemple dans la doc de l'API :/

**Comment by pgrimaud** [comment]
C'est la destination qui n'est pas la valide.

Si tu regardes cette ressource : 
http://api-ratp.pierre-grimaud.fr/v2/metros/7

Les destinations possibles sont : 

`mairie+d+ivry+villejuif+louis+aragon`
et
`la+courneuve+8+mai+1945`

Tu peux regarder 
http://api-ratp.pierre-grimaud.fr/v2/metros/7/stations/poissonniere?destination=mairie+d+ivry+villejuif+louis+aragon
ou
http://api-ratp.pierre-grimaud.fr/v2/metros/7/stations/poissonniere?destination=la+courneuve+8+mai+1945

**Comment by KisaW** [comment]
Autant pour moi, j'ai mal lu alors :)

**Comment by pgrimaud** [comment]
Pas de soucis, bonne journée :)

**Comment by robinduval** [comment]
Salutation,

J'ai vu que pas mal de personnes remonté le même soucis ;)
Peut-être qu'il faudrait renommer destination en terminus, qu'en penses tu ?

Merci pour ton api.

**Comment by pgrimaud** [comment]
Hello @robinduval, 

J'ai repris le terme utilisé par la RATP sur son site.

"Terminus" est assez ambigu dans certains cas :

- Sur les lignes de RER où il y a plusieurs branches. J'ai l'info du terminus, mais impossible de filtrer sur cette valeur. Par exemple si tu demandes les trains du RER B en direction de Massy, tu n'auras pas les trains qui vont à Robinson alors qu'ils s'arrêtent aux mêmes gares.

- Ou lorsqu'il y a des travaux / problèmes de trafic, le vrai terminus est amené à changer
