### ISSUE TITLE
ID incorrects 

### ISSUE THREAD

**Issue by GuillaumeNury** [pgrimaud/horaires-ratp-api#16]
Bonjour,
Lorsque j'appelle `/v2/metros/8/stations/275?destination=23`, je reçois :
```javascript
"destination": {
   "id": "23",
   "name": "Balard",
   "slug": "balard"
}
```
La station Balard a donc un `id = 23`.

Si on appelle `/v2/metros/8/stations`, on obtient :
````javascript
"stations": [
{
   "id": "341",
   "name": "Balard",
   "slug": "balard"
},
...
]
```

Ici, balard a un `id = 341` !

De plus, `/v2/metros/8/stations/daumesnil?destination=balard` fonctionne, mais pas `/v2/metros/8/stations/balard?destination=daumesnil`.

**Comment by pgrimaud** [comment]
Bonsoir @GuillaumeNury,

Je viens juste de modifier l'API afin de clarifier la signification des id :

**Les ressources destinations sont indépendantes des ressources stations. Par conséquent elles n'ont pas le même id, même si elles partagent la valeur name ou slug.**

Les stations sont dépendants des stations.

Ce qui veut dire que l'id de la station balard de la ligne 8 est ``341``, et que l'id de la destination balard est ``23``.

Maintenant avec ``/v2/metros/8/stations/275?destination=23`` tu auras : 

```
{
       "id_destination": "23",
       "destination": "Balard",
       "slug": "balard"
}
```

et ``/v2/metros/8/stations`` :

```
"stations": [
          {
              "id_station": "341",
              "name": "Balard",
              "slug": "balard"
          }
]
```

En ce qui concerne ``/v2/metros/8/stations/balard?destination=daumesnil``, tu ne peux utiliser dans la destination que l'une des deux valeurs des terminus, c'est à dire ``balard`` ou ``pointe+du+lac``.

``/v2/metros/8/stations/balard?destination=pointe+du+lac`` sera donc la ressource valide. :)

**Comment by GuillaumeNury** [comment]
Merci pour ces précisions !
Bonne soirée
