### ISSUE TITLE
Ajout fonctionalité

### ISSUE THREAD

**Issue by pipersw** [pgrimaud/horaires-ratp-api#17]
Actuellement on peut avoir les horaires en fonction de la destination et de la station.
Pouvez-vous ajouter une requête permettant d'avoir les horaires des trains entre une station de départ et une station d'arrivée ?
La requête pourrais être par exemple: http://api-ratp.pierre-grimaud.fr/v2/{TypeLigne}/{LigneId}/stations/depart={StationId}?arrivee={StationId}?destination={DestinationId}

**Comment by pgrimaud** [comment]
Hello @pipersw,

Si je prends un exemple concret:
http://api-ratp.pierre-grimaud.fr/v2/metro/6/stations/depart=bercy?arrivee=daumesnil&destination=nation

Ce qui renverrait les horaires des trains du metro 6 en direction de nation aux stations **bercy**, **dugommier** et **daumesnil** ?

**Comment by pipersw** [comment]
C'est presque ca, mais sans les stations intermédiaires. Si je prends un
exemple sur le RER B :
http://api-ratp.pierre-grimaud.fr/v2/metro/6/stations/depart=massy-palaiseau?arrivee=laplace&destination=st-remy-les-chevreuse
<http://api-ratp.pierre-grimaud.fr/v2/metro/6/stations/depart=bercy?arrivee=daumesnil&destination=nation>
Il y a une liste de trains qui partent de Massy Palaiseau en direction de
st-remy, mais je voudrais un filtrage sur ceux qui s’arrêtent à Laplace,
car tous ne s'y arrêtent pas.

Le 12 avril 2016 à 18:56, Pierre Grimaud <notifications@github.com> a écrit
:

**Comment by pgrimaud** [comment]
J'avais déjà commencé cette même feature. Je me basais sur les noms de trains en 4 lettres (WRWN, YVAN, NEMO, etc...). 

J'en ai recensé plus de 400 pour l'instant, c'est un peu touchy à mettre en place, mais pas impossible :)

**Comment by pipersw** [comment]
Oui en effet ca fait beaucoup si tu stockes tous les noms des trains dans
une base de donnée. Ce ne serais pas plus simple de trouver les noms des
trains en commun entre les 2 stations ?

Le 13 avril 2016 à 10:58, Pierre Grimaud <notifications@github.com> a écrit
:

**Comment by pgrimaud** [comment]
@pipersw Je vais plancher là dessus. Le seul hic, c'est qu'entre 2 stations très éloignées tu n'auras pas les mêmes trains.

**Comment by pgrimaud** [comment]
@pipersw Voilà, je te laisse tester, dis moi si c'est ok :smile: 
https://github.com/pgrimaud/horaires-ratp-api/tree/master#nouveaut%C3%A9-v22--gare-darriv%C3%A9e-uniquement-pour-les-rer-beta

**Comment by pipersw** [comment]
c'est ok, super !!

**Comment by pipersw** [comment]
Petit bug : ce matin on regarde les horaires des trains RERB entre massy palaiseau et laplace, il est 9h, et la requette est : [api-ratp.pierre-grimaud.fr/v2/rers/B/stations/massy+palaiseau?destination=charles+de+gaulle+mitry+claye&endingstation=laplace](url)
On a comme résultats: EPAF 9:45 et ERIC 9:49.

Arrivé à la gare de massy palaiseau dix minutes plus tard, on a sur le panneau:
EPAF 9:30
ERIC 9:34
EPAF 9:45
ERIC 9:49

On a donc un décalage de 2 trains.
Hormis ce décalage, ca fonctionne.

**Comment by pgrimaud** [comment]
@pipersw Merci pour ton retour !
Je pense avoir trouvé le problème, dis moi si tu vois autre chose. :)

**Comment by pgrimaud** [comment]
@pipersw Après 2 semaines de tests positifs, je clôture l'issue. :)
