### ISSUE TITLE
horaires ne fonctionnent pas en utilisant les slugs

### ISSUE THREAD

**Issue by zandu** [pgrimaud/horaires-ratp-api#19]
Bonjour Pierre,

Je joue un peu avec les horaires, et je n'arrive pas à en faire marcher d'autres que celui qui est en exemple: http://api-ratp.pierre-grimaud.fr/v2/metros/8/stations/daumesnil?destination=balard

Pour tous les autres (exemple: http://api-ratp.pierre-grimaud.fr/v2/metros/8/stations/balard?destination=boucicaut), je me mange une 404.

Est-ce un bug ou un problème entre la chaise et le clavier?

Merci!

**Comment by zandu** [comment]
ok c'est un doublon, il fallait utiliser un terminus :)
je ferme!

**Comment by pgrimaud** [comment]
La tristesse, j'étais en train de répondre :smile:
