### ISSUE TITLE
Noctilien

### ISSUE THREAD

**Issue by YodahJimah** [pgrimaud/horaires-ratp-api#20]
Bonjour. Dans l'attente de l'ouverture officielle des données temps réel, j'avais commencé (comme beaucoup de monde) à parser directement les résultats des pages wap pour mon projet de page unique reprenant tous les départs autour de chez moi. Jusqu'à ce que je tombe sur cette API...
Juste une chose me manque, serait-il possible d'ajouter les lignes de Noctilien sur le même modèle que les lignes de bus diurnes?
L'appel pourraît être sous la forme
http://api-ratp.pierre-grimaud.fr/v2/noctiliens/N11/stations/porte+de+vincennes?destination=pont+de+neuilly

**Comment by pgrimaud** [comment]
Hello, ça m'a l'air jouable.
Je te fais ça ASAP.

**Comment by YodahJimah** [comment]
Ce serait super :) De mon côté il faudra encore que je prépare mon script à charger les lignes en fonction de l'heure pour pas charger ton serveur inutilement en appelant du Noctilien en pleine journée… En journée ça donne ça comme utilisation :
http://pitich.at/transports/

**Comment by pgrimaud** [comment]
Vraiment classe ta page ! Bravo ! 😄 
Je vais tenter de faire une nuit blanche ce soir ou demain, pour pouvoir gérer les horaires des noctiliens.

**Comment by V20100T** [comment]
En effet
bel écran ,
Et je pense que nous sommes voisins

En fait Pierre pourait connecter tout les voisins entre eux
car on veut tous les horaires de nos transport ;)


Merci a toi PG

**Comment by pgrimaud** [comment]
@YodahJimah Hello, j'ai ajouté les horaires des noctiliens la nuit dernière. 
La listes des lignes est disponible ici : http://api-ratp.pierre-grimaud.fr/v2/noctiliens

**Comment by YodahJimah** [comment]
Merci beaucoup, hâte de tester ça une de ces prochaines nuits pour pouvoir remplacer mon code barbare de parsing des pages ratp.fr qui ralentit l'affichage de mes pages la nuit...

En revanche, il est normal que la ligne circulaire N02 ait deux directions, quand la N01 n'en a bien qu'une seule ?

**Comment by pgrimaud** [comment]
@YodahJimah Ouais, c'est une ligne circulaire. Y'a qu'un seul sens du coup : http://www.ratp.fr/informer/pdf/orienter/f_plan.php?loc=noctilien&nompdf=n01&fm=gif

**Comment by YodahJimah** [comment]
Justement, c'est pas la N01 le problème, c'est la N02 qui a deux directions alors qu'elle devrait n'en avoir qu'un...

**Comment by pgrimaud** [comment]
Exact, ce que je viens de vérifier. Je viens donc de modifier la destination du N02. 
Merci.

**Comment by YodahJimah** [comment]
Le mystère du N02 s'épaissit... L'API ne renvoie aucun résultat avec le terminus "gare+montparnasse":
```
                "destination": "Gare Montparnasse",
                "message": "Service terminé ou horaires indisponibles"
```
Sur le site de la RATP, la recherche des horaires Noctiliens propose de choisir une direction entre "circulaire" et "circulaire", probablement correspondant à tes deux précédentes directions "circulaire-a" et "circulaire-r".
L'un des deux renvoie vers une page "Votre demande n'a pas été comprise.", l'autre donne bien les horaires.

> Les prochains passages
> Terminus	Temps d'attente
> Circulaire Exterieure	9 mn
> Circulaire Exterieure	24 mn

Les URL des pages qui fonctionnent donnent par exemple
...prochains_passages/PP/BN02/N02_401/R (Bastille)
...prochains_passages/PP/BN02/N02_386/R (Vavin)
...prochains_passages/PP/BN02/N02_425/R (Saint Guillaume)
donc quelle que soit la position de l'arrêt sur la boucle par rapport à Montparnasse, c'est toujours le Retour qui existe, pas l'Aller.
Je pense que ta transformation du terminus en "gare montparnasse" bugue pour récupérer les résultats. Peut-être peux-tu revenir à une direction "circulaire-r" comme à l'origine et juste faire sauter la destination "a" ?

**Comment by pgrimaud** [comment]
@YodahJimah Bien vu, je viens de corriger ça : 
http://api-ratp.pierre-grimaud.fr/v2/noctiliens/N02/stations/9627?destination=gare+montparnasse
