### ISSUE TITLE
ID de la station La courneuve Ligne 7

### ISSUE THREAD

**Issue by laliace** [pgrimaud/horaires-ratp-api#21]
http://api-ratp.pierre-grimaud.fr/v2/metros/7/stations/ indique que la Station la courneuve ligne 7 a pour ID 306
alors que quand on requete va le slugid,  son id est 19
exemple  : http://api-ratp.pierre-grimaud.fr/v2/metros/7/stations/288?destination=la+courneuve+8+mai+1945

**Comment by laliace** [comment]
Ajoutant Bonjour au départ de mon message
et merci pour cette API à la fin
:)

**Comment by pgrimaud** [comment]
Hello @laliace,

Les stations sont dépendants des destinations.

Ce qui veut dire que l'id de la station "La courneuve" de la ligne 7 est ``306``, et que l'id de la destination "La courneuve" est ``19``.

Maintenant avec ``/v2/metros/7/stations/288?destination=19`` tu auras : 

```
"destination": {
    {
           "id_destination": "19",
           "name": "La Courneuve 8 mai 1945",
           "slug": "la+courneuve+8+mai+1945"
    }
}
```

et ``/v2/metros/7/stations`` :

```
"stations": [
          {
              "id": "306",
               "name": "La Courneuve - 8 Mai 1945",
               "slug": "la+courneuve+8+mai+1945"
          }
]

J'ai un peu fait de la merde lors de mon implémentation haha, ça aurait été plus simple si les deux avaient le même ID. :(
