### ISSUE TITLE
horaires ligne B

### ISSUE THREAD

**Issue by Mboutin** [pgrimaud/horaires-ratp-api#22]
Bonjour Pgrimaud,

J'ai utilisé tes liens pour faire un petit dashboard avec les horaires des bus et rer des environs de mon immeuble et depuis ce matin, les horaires de la ligne B ne sont plus disponibles.
Voilà ce que me renvois la requête "http://api-ratp.pierre-grimaud.fr/v2/rers/b/stations/laplace?destination=4":
{
    "response": {
        "code": "404",
        "message": "Ressource not found"
    },
    "_meta": {
        "version": "2",
        "date": "2016-06-07T14:45:57+02:00",
        "call": "GET /rers/b/stations/laplace?destination=4"
    }
}

Les horaires des bus, eux, marchent très bien.

En tout cas je te remercie pour ton travail, il m'aide beaucoup a comprend comment fonctionnent les API.

**Comment by pgrimaud** [comment]
Hello@Mboutin !
Merci du retour, je viens de corriger ça. 
C'était lié à l'ajout des horaires des noctiliens :(

Bonne journée

**Comment by Mboutin** [comment]
Je viens de voir que c'est effectivement revenu =) 
je te remercie encore une fois ;) 

Bonne journée à toi aussi
