### ISSUE TITLE
404 sur une ressource valide

### ISSUE THREAD

**Issue by Quen98** [pgrimaud/horaires-ratp-api#24]
Hello,

Lorsque l'on tape sur
http://api-ratp.pierre-grimaud.fr/v2/bus/47/stations
Et que l'on prend deux ids au hards, par exemple id 2588 et 2955 pour former l'url suivante
http://api-ratp.pierre-grimaud.fr/v2/bus/47/stations/2688?destination=2955
L'API nous retourne un 404 resource not found

Il est probable que l'erreur vienne de moi, mais je préfère vérifier quand même :)
Merci

**Comment by pgrimaud** [comment]
Hello,
Il faut rentrer une id_destination comme paramètre destination.
Tu peux les trouver à cette adresse : http://api-ratp.pierre-grimaud.fr/v2/bus/47

Dans ce cas là, tes urls seront : 
http://api-ratp.pierre-grimaud.fr/v2/bus/47/stations/2588?destination=176
http://api-ratp.pierre-grimaud.fr/v2/bus/47/stations/2588?destination=193

Bonne soirée

**Comment by Quen98** [comment]
Effectivement, merci beaucoup pour l'explication :)
