### ISSUE TITLE
https endpoint for API

### ISSUE THREAD

**Issue by arizona2014** [pgrimaud/horaires-ratp-api#25]
Hi Pierre,

Great work with your API and app. I'm trying at the moment to access your API data on a system which only accepts https requests, so is there any link with https protocol for your API ?

Thanks

**Comment by pgrimaud** [comment]
Hi Andy,

I just switched all endpoints to https. 

Tell me if's ok for you.

**Comment by arizona2014** [comment]
Thanks Pierre , works flawlessly
