### ISSUE TITLE
Afficher les horaires de plusieurs stations

### ISSUE THREAD

**Issue by Doxaid** [pgrimaud/horaires-ratp-api#27]
Bonjour,

Merci pour le partage du projet :)

Serait il possible d'afficher les horaires de plusieurs stations dans la même page ? (Métro(s), bus, Tram)

Merci d'avance pour la réponse,
![mouton 38](https://cloud.githubusercontent.com/assets/23442380/20251074/3a3008da-aa16-11e6-8152-7a2e7067e028.png)
![mouton ligne4](https://cloud.githubusercontent.com/assets/23442380/20251075/3a30ea84-aa16-11e6-9d8a-258014ba43fe.png)

**Comment by pgrimaud** [comment]
Hello,

Oui c'est tout à fait possible, il n'y a pas de limitation sur l'API.
D'où vient ce screenshot ?

**Comment by Doxaid** [comment]
Hello,

Les deux screenshot correspondent aux rendus des pages index.html fournis avec le projet (avec une mise en forme différente). 

J'aurais souhaité afficher dans la même page index.html plusieurs stations (plutôt que de multiplier les sites).

**Comment by pgrimaud** [comment]
Oui c'est possible. Il suffit d'ajouter des lignes dans la promesse du fichier main.js.

```js
var schedules_url1 = 'http://api-ratp.pierre-grimaud.fr/v2/rers/b/stations/arcueil+cachan?destination=4';
var schedules_url2 = 'http://api-ratp.pierre-grimaud.fr/v2/rers/b/stations/arcueil+cachan?destination=3';
var traffic_url = 'http://api-ratp.pierre-grimaud.fr/v2/traffic/rers/b';

$.when($.getJSON(schedules_url1), $.getJSON(schedules_url2), $.getJSON(traffic_url)).done(function(schedules1, schedules2, traffic) {
      var data = {};
      data.traffic = traffic[0].response.message;
      data.line = schedules[0].response.informations.line;
      ... (voir main.js)
      data.station = schedules[0].response.informations.station.name;

      data.line2 = schedules[0].response.informations.line;
      ... (voir main.js)
      data.station2 = schedules[0].response.informations.station.name;

      var date = new Date(),
          hours = date.getHours(),
          minutes = date.getMinutes();
      data.current_time = (hours < 10 ? '0' + hours : hours) + ':' +
                          (minutes < 10 ? '0' + minutes : minutes);

      $content.html(template(data));
});
```

Tout en sachant que l'url associée à schedules_url2 peut être une ressource metro, rer, bus ou tram.
Pour finir, il suffit de d'adapter la vue et de rajouter l'affichage des nouvelles valeurs.

Je ne sais pas si c'est clair, il est tard et je suis un peu fatigué. 😴

**Comment by Doxaid** [comment]
Ça marche nickel. Merci beaucoup :)
