### ISSUE TITLE
Détails d'une station

### ISSUE THREAD

**Issue by cedricrey** [pgrimaud/horaires-ratp-api#28]
Bonjour,

Tout d'abord merci pour votre API, c'est vraiment très utile et pratique.
Serait il envisageable d'avoir les détails d'une station sans nécessairement l'associer à une ligne ?
Par exemple, savoir quelle(s) ligne(s) passent dans un hub (ex : Gare de Lyon) https://api-ratp.pierre-grimaud.fr/v2/stations/gare+de+lyon 
`{"metros": [
            {
                "line": "1",
                "destinations": [
                    {
                        "id": "5",
                        "name": "Château de Vincennes",
                        "slug": "chateau+de+vincennes"
                    },
                    {
                        "id": "6",
                        "name": "La Défense",
                        "slug": "la+defense"
                    }
                ]
            },
            {               
                "line": "14",
                "destinations": [
                    {
                        "id": "34",
                        "name": "Saint-Lazare",
                        "slug": "saint+lazare"
                    },
                    {
                        "id": "35",
                        "name": "Olympiades",
                        "slug": "olympiades"
                    }
                ]
            }],
"rers" : [
            {
                "line": "A",
                "destinations": [
                    {
                        "id": "1",
                        "name": "St-Germain-en-Laye Poissy-Cergy",
                        "slug": "st+germain+en+laye+poissy+cergy"
                    },
                    {
                        "id": "2",
                        "name": "Boissy-St-Léger Marne-la-Vallée",
                        "slug": "boissy+st+leger+marne+la+vallee"
                    }
                ]
            }]
}`
Sachant que les ids des stations ne sont pas les mêmes suivants les transports, j'imagine que cela peut être complexe (et il faudrait donc ajouter les id de station dans la réponse d'une requête par slug pour chaque transport si le slug correspond à plusieurs id)

**Comment by pgrimaud** [comment]
Hello,

J'avais pensé à une feature de ce style. C'est vite problématique sur les stations qui comportent beaucoup de lignes. (ex République, St Lazare ou Châtelet). Et encore, je ne parle que des métros, imaginez le cumule metro + bus + rer + tram (la totale). D'ailleurs, aucune station ne présente ces 4 modes de transports 🤔 

Et même pour certaines stations avec une seule ligne, le temps de réponse varie grandement. J'ai benché ça y'a quelques temps et on peut se retrouver avec : une réponse rapide (< 1 seconde) pour les horaires dans un sens, et une réponse lente (> 5 secondes) pour les horaires dans une autre ligne. (Malheureusement je suis dépendant du site de la ratp, qui ne réagit jamais de la même façon).

Je pense donc que le mieux reste encore de faire des appels distincts en parallèle, ce qui vous permettra d'optimiser grandement le temps de chargement.

Désolé 😞

**Comment by cedricrey** [comment]
Oui je suppose bien qu'une info des passage temps réel est complexe. C'est bien pour cela que je voulais faire les appels en parallèle. Mais je cherchais surtout à avoir un référentiel, dans le cas d'une recherche de station, simplement obtenir les lignes y passant afin de construire ensuite les appels aux horaires.
Cela dit après réflexion, je crois que ca risque d'être trop complexe, les stations ne partageant pas le même nom entre les différents réseaux, certaines lignes s'arrêtant plusieurs fois sur un même "hub" (ligne 4 a Chatelet et Les Halles) ou plusieurs fois le même nom (genre Gare de Lyon sur les bus ou La Défense sur la 1). 
Merci d'avoir pris le temps de me répondre. 

Cédric
