### ISSUE TITLE
Code source de l'API ? 

### ISSUE THREAD

**Issue by flemzord** [pgrimaud/horaires-ratp-api#31]
Bonjour, 

J'aimerais savoir si il existe un repo sur l'API ? 
Ainsi, nous pourrions contribuer dedans et surtout l'héberger autre part (résilience) 

Maxence

**Comment by pgrimaud** [comment]
Hello,

Non pas de repo, pour des raisons légales. (Scrapping du site ratp.fr).
Mais j'ai pour projet de créer un sdk qui consume l'api créée pour leurs applications Android et iOS.

Si ça t'intéresse, fais moi signe.

**Comment by carfup** [comment]
Bonjour,

Pour rejoindre Maxence, depuis que la RATP a "ouvert" ses données en temps réel, cela pourrait être intéressant d'ouvert un repo et de pouvoir travailler ensemble là dessus.

Du coup, tu le devines Pierre, cela m'intéresse :)

Clément

**Comment by pgrimaud** [comment]
Hello @carfup, je n'ai pas encore eu le temps de regarder l'API de la RATP. Vaut-elle le coup qu'on développe un SDK pour travailler dessus, ou de se lancer sur un scraper de l'app iOS / Android ?

La demande d'accès via un formulaire pdf à envoyer par email ainsi que l'idée d'être bloqué sur un scope d'IP me refroidit pas mal... De plus j'ai lu qu'il y avait un cache de 5 minutes. Et puis le wsdl...
C'est cool de mettre ces données à disposition et ça a dû être compliqué de leur part, mais en 2017 on pourrait s'attendre à bien mieux.

Donc à réfléchir dans les semaines à venir. Mais ça vaudrait ptet le coup de créer un scraper ou une doc de leur webservice utilisé sur leurs applications mobiles.

**Comment by Varal7** [comment]
Bonjour @pgrimaud, @carfup,

J'ai rempli ce fameux formulaire d'inscription et me suis amusé à coder une première version de wrapper de l'API.

Le code est disponible ici : https://github.com/Varal7/opendata-ratp

Je propose une démo depuis [mon serveur perso.](http://ratp.varal7.fr). Par exemple, pour obtenir les horaires du RER A depuis Auber en direction de l'Est : 
http://ratp.varal7.fr/?line=RA&station=Auber&direction=R
http://ratp.varal7.fr/api.php?line=RA&station=Auber&direction=R

**Comment by pgrimaud** [comment]
Merci @Varal7 pour ton retour.
Leur API a l'air de bien répondre (pas de cache, alléluia \o/).

Reste juste à gérer leur SOAP dégueux et la restriction d'IP 🤔

**Comment by V20100T** [comment]
Hello, 

Merci pierre pour cette api

Je vous propose ma petite UI basée sur ton api
https://v20100t.github.io/live-ratp/
C est pas fini mais ça fonctionne.


Pour ne pas être complétement hors sujet 
j attire votre attention sur ce site d apis
https://opendata.paris.fr/explore/dataset/stations-velib-disponibilites-en-temps-reel/
https://opendata.paris.fr/explore/dataset/voiesactuellesparis2012/

Je pense qu il va nous falloir une surcouche à toutes les api "open data"
pour éviter les tokens et demandes officielles 
@Varal7 
Ajouter ton api ce bouquet d apis opendata-paris.fr ?

@pgrimaud 
Pour ton api pourrait tu mettre une surcouche avec les geoloc des stations et quelques infos statiques en plus ?

En tout cas merci a vous les mecs
Bonne soirée

**Comment by losynix** [comment]
Salut ! Je travaille actuellement sur un [client console](https://i.imgur.com/HAZEdg5.png) basé sur ton API  et comme @flemzord j'aimerais pouvoir héberger le backend chez moi pour la résilience. Je serais donc aussi très intéressé par un wrapper sur leur nouvelle API pour avoir du JSON (pas très envie de toucher au SOAP...).

Merci pour ton travail en tous cas !

**Comment by pgrimaud** [comment]
Hello @flemzord & @losynix,

Voilà un back-end minimaliste, mais distribuable : https://github.com/pgrimaud/ratp-api-rest

Enjoy

**Comment by ybarbaria** [comment]
Bonjour à tous, 

Vous pouvez utilisez mon api à cette url : https://barbaria.io/ratp/
Vous pouvez aussi m'aider et/ou me donner des conseils sur l'app node que j'ai créé.

Il s'agit d'une api réalisée via node et restify. 

Merci :)
