### ISSUE TITLE
Api ratp? 

### ISSUE THREAD

**Issue by ybarbaria** [pgrimaud/horaires-ratp-api#32]
Salut, 

J'aimerai connaître l'url de l'api que tu consomme pour récupérer les données que tu fourni via ton api? 

Merci :) 

Yvan

**Comment by pgrimaud** [comment]
Hello, je me base directement sur le site ratp.fr

**Comment by ybarbaria** [comment]
Merci Pierre, 

Ok du coup tu parse la page, aucun problème avec la ratp? 
Est ce que tu vois un inconvénient à ce que j'utilise ton api à des fins persos? 
Sinon je ferais un parse de la page web. 

Merci

Yvan

**Comment by pgrimaud** [comment]
Pas de soucis avec la RATP, je n'ai pas reçu de plaintes. 

Oui bien sûr, je l'ai créée à la base pour développer de petites applications persos. Donc tu peux l'utiliser comme bon te semble ! 

Pierre
