### ISSUE TITLE
Linux GnomeShell Extension

### ISSUE THREAD

**Issue by dlallemand** [pgrimaud/horaires-ratp-api#34]
Bonjour,

D'abord, merci pour cette API !
Je me suis autorisé à l'utiliser pour "bricoler"  une extension gnome-shell (OS Linux). Dans le sens où je m'appuie sur votre travail, je voulais vous en faire part...:-)

https://github.com/dlallemand/gnomeshell-traffic-ratp

Salutations,

**Comment by pgrimaud** [comment]
Hello,

Désolé pour le temps de réponse, j'ai eu une fin d'année assez chargée...

Bravo pour l'extension, ça rend vraiment bien ! Merci de m'avoir prévenu, ça fait plaisir de voir les diverses utilisation de l'API. 😄 

J'ai comme projet de développement le même type d'extension pour MAC, en swift.

Bonne soirée
