### ISSUE TITLE
Mairie de Montrouge

### ISSUE THREAD

**Issue by gregcha** [pgrimaud/horaires-ratp-api#36]
Cette station est manquante (la seule parmi les métros à priori*). Il s'agit du terminus de la ligne 4. 

*avec les funiculaires mais j'imagine qu'ils ne sont pas gérés par la ratp

**Comment by pgrimaud** [comment]
Hello, merci de l'info. Je viens de la rajouter. 

Hélas non, les funiculaires sont indépendants.

**Comment by gregcha** [comment]
Bim! Canon 👍
