### ISSUE TITLE
Traitement de Chatelet (les Halles) selon RER A ou B

### ISSUE THREAD

**Issue by gregcha** [pgrimaud/horaires-ratp-api#37]
Pourquoi traiter différemment cette station selon que l'on soit sur le RER A ou B ? (id 8 ou 41)
On aurait pu imaginer un traitement similaire à celui des stations de métros disposant de plusieurs lignes, non ? Cela implique une logique spécifique pour Chatelet (dans mon cas). 

J'en profite pour vous remercier pour cette excellente API.
D'autant plus quand on voit ce que vient de sortir la ratp...

**Comment by pgrimaud** [comment]
Tout simplement parce que sur le site de la RATP ces stations ne sont pas nommées pareil (woohoo...) : 

http://www.ratp.fr/horaires/fr/ratp/rer/choix-arret-direction/RA
Châtelet-Les-Halles pour le RER A
 
http://www.ratp.fr/horaires/fr/ratp/rer/choix-arret-direction/RB
Châtelet pour le RER B

Du coup, je ne peux malheureusement pas lier ces deux stations, vu que l'url à parser diffère (chatelet-les-halles pour le A et chatelet pour le B 😞 ).

Je manque de temps et je n'ai pas encore regardé l'API RATP. Cela donne quoi ? Les données sont bonnes ? 
J'ai lu qu'il y avait un cache de 5 minutes ? Fake ou non ?

Merci d'avance pour ton retour

**Comment by gregcha** [comment]
Hello merci pour ces précisions, je me doutais que cela partait d'une contrainte :) 

Concernant leur API, je n'ai malheureusement pas encore pu y accéder. 
Entre le process d'inscription d'un autre âge, une doc indigeste à souhait et une techno sur laquelle je suis pas du tout à l'aise, j'hésite vraiment à me lancer dans l'aventure. 

D'autant que j'ai une appli fonctionnelle grâce à toi !
