### ISSUE TITLE
Horaires Bus 186 ?

### ISSUE THREAD

**Issue by sbouba** [pgrimaud/horaires-ratp-api#38]
Bonjour,

tout d'abord bravo et merci pour cette API, bien plus simple à utiliser que celle en SOAP de la RATP.

J'aimerais comprendre pourquoi je n'arrive pas à voir les horaires de bus de la ligne 186. A partir des stations :
```
https://api-ratp.pierre-grimaud.fr/v2/bus/186/stations
{
    "response": {
        "stations": [
            {
                "id": "5416",
                "name": "3 Communes",
                "slug": "3+communes"
            },
           ...
            {
                "id": "1782",
                "name": "Porte d'Italie",
                "slug": "porte+d'italie"
            },
            ...
        ]
    },
    "_meta": {
        "version": "2",
        "date": "2017-01-22T21:28:11+01:00",
        "call": "GET /bus/186/stations"
    }
}
```

J'essaye de voir les horaires de passage :
```
https://api-ratp.pierre-grimaud.fr/v2/bus/131/stations/3+communes?destination=porte+d%27italie
https://api-ratp.pierre-grimaud.fr/v2/bus/131/stations/5416?destination=1782
```

Mais les deux me retournent une 404. Si j'ouvre l'appli de la RATP, j'ai bien les horaires de passages qui s'affichent. Où est ce que je me trompe ?

Merci pour votre aide,

Ruben

**Comment by pgrimaud** [comment]
Hello,

Il faut utiliser l'id destination qui se trouve ici (les id stations et destinations ne sont pas les mêmes): 

```
https://api-ratp.pierre-grimaud.fr/v2/bus/186
```

Donc https://api-ratp.pierre-grimaud.fr/v2/bus/186/stations/5416?destination=126 fonctionne :)

**Comment by ruben-podadera** [comment]
Merci !

C'est très curieux qu'une station n'ait pas le même IDs suivant le contexte ...

Vous pouvez fermer cette issue 👍

**Comment by pgrimaud** [comment]
@ruben-podadera Simplement une erreur de jeunesse... 😞

**Comment by sbouba** [comment]
Je vous montre ce à quoi vous avez contribué :
[image: Images intégrées 1]

Reste encore du boulot, mais sur le principe ça marche bien :-) Merci !

2017-01-23 10:42 GMT+01:00 Pierre Grimaud <notifications@github.com>:

**Comment by sbouba** [comment]
@pgrimaud Je vous montre ce à quoi vous avez contribué :
![img_20170123_231019](https://cloud.githubusercontent.com/assets/2707070/22225397/9a026b34-e1c2-11e6-86ec-41addfc9b7c9.jpg)

**Comment by pgrimaud** [comment]
@sbouba Oh magnifique ! 😀 😀 ça tourne avec quoi ?
