### ISSUE TITLE
Demande liste des transports sur base url de l api

### ISSUE THREAD

**Issue by V20100T** [pgrimaud/horaires-ratp-api#39]
Hello Pierre,

Pour faire une UI  dynamique full ton API
https://v20100t.github.io/live-ratp/

Est ce possible d avoir 

- la liste des transports sur la base de l url de ton api

https://api-ratp.pierre-grimaud.fr/v2/
=> liste des transports en json

-  geoloc des stations
-- https://data.ratp.fr/explore/dataset/positions-geographiques-des-stations-du-reseau-ratp/table/?disjunctive.stop_name&disjunctive.code_postal&disjunctive.departement&location=9,48.86463,2.39716

- code couleur html des stations
https://data.ratp.fr/explore/dataset/indices-et-couleurs-de-lignes-du-reseau-ferre-ratp/
https://github.com/V20100T/live-ratp/tree/master/css

Merci
Bonne soirée

**Comment by pgrimaud** [comment]
Hello ! Merci pour tes recommendations. Je bosse actuellement sur une v3, qui se base sur la nouvelle API de la RATP en SOAP. Je vais intégrer ces améliorations sur cette v3, mais par contre je n'ai pas de date de sortie...

**Comment by V20100T** [comment]
ok ca marche,
Merci pour ton retour, 
on attend la v3 alors.


Tu devrais aussi faire un post avec tous les projets 
gravitant autour de ton api ,
il doit y avoir quelques pepites ;)


Bonne journée

**Comment by yehoudatech** [comment]
Bonne Idée !
