### ISSUE TITLE
Prolongement T6

### ISSUE THREAD

**Issue by guidugui** [pgrimaud/horaires-ratp-api#40]
Bonjour,

Est-il prévu d'intégrer le prolongement du T6 ? (Les gares de Viroflay rive gauche et Viroflay rive droite, ainsi que la mise à jour du terminus qui est Robert Wagner actuellement).

Il me semble également que la station Vélizy 2 est manquante sur le T6, est-il prévu de la rajouter ?

Merci, et bravo pour cette API très pratique !

**Comment by pgrimaud** [comment]
Hello,

Merci beaucoup pour l'info. Vélizy 2 a été oublié, et je viens de rajouter les 2 nouvelles stations manquantes!

Bonne journée

**Comment by guidugui** [comment]
Wahou c'est du rapide !! Super, merci beaucoup ! :)

Bonne journée à vous et bonne fin de weekend.

**Comment by pgrimaud** [comment]
🚀 👍
