### ISSUE TITLE
Erreur récupération horaires sur Bus 21

### ISSUE THREAD

**Issue by kalon33** [pgrimaud/horaires-ratp-api#41]
Bonjour,

quand j'essaie de récupérer les horaires du 21 à l'arrêt saint-lazare, https://api-ratp.pierre-grimaud.fr/v2/bus/21/stations/gare+saint+lazare??destination=stade+charlety-porte+de+gentilly

J'obtiens une erreur 400.

Et sur un autre arrêt: https://api-ratp.pierre-grimaud.fr/v2/bus/21/stations/saint+jacques-gay+lussac?destination=gare+saint+lazare

Erreur 404.

Pourtant, ces deux stations sont dans la liste là: https://api-ratp.pierre-grimaud.fr/v2/bus/21/stations

Que fais-je de mal ? Merci d'avance pour votre aide.

**Comment by pgrimaud** [comment]
Hello @kalon33 , la destination est :
```
gare+saint-lazare
```
et non :
```
gare+saint+lazare
```
Du coup les appels valides sont : 

https://api-ratp.pierre-grimaud.fr/v2/bus/21/stations/stade+charlety-porte+de+gentilly?destination=gare+saint-lazare
et 
https://api-ratp.pierre-grimaud.fr/v2/bus/21/stations/saint+jacques-gay+lussac?destination=gare+saint-lazare

Bonne journée !

**Comment by kalon33** [comment]
@pgrimaud On ne devrait jamais tester de nouvelles choses de bon matin ! Merci ! Du coup pour les infos traffic, bientôt sur les bus aussi ?

**Comment by kalon33** [comment]
@pgrimaud https://api-ratp.pierre-grimaud.fr/v2/bus/21/stations/gare+saint-lazare?destination=stade+charlety-porte+de+gentilly (qui est le départ de l'autre terminus de la ligne, j'ai juste inversé les deux arguments), ne fonctionne pas...

**Comment by pgrimaud** [comment]
Pas de soucis 😄 . Oui, le trafic des bus est prévu dans la v3, ainsi que le trafic du RER C, D, E et transilien.

Tu as la liste des destinations ici : https://api-ratp.pierre-grimaud.fr/v2/bus/21
https://api-ratp.pierre-grimaud.fr/v2/bus/21/stations/gare+saint+lazare?destination=porte+de+gentilly

Les slugs ne sont pas les mêmes entre les destinations et stations. (Je me suis basé sur ceux proposés par la RATP...). Mais tout ça sera normalisé dans la v3.

(v3 disponible dans moins de 10 jours. #teasing)

**Comment by kalon33** [comment]
@pgrimaud chouette merci ! Du coup sera-t-il aussi alors possible de demander par exemple les horaires de tous les bus et/ou trains passant à un arrêt donné ? Dans mon cas, j'ai la 21 et la 27 sur le même trajet, mais j'imagine que la notion de "Terminal" regroupant tous les arrêts aux noms voisins serait pratique (j'entrevois déjà l'utilité pour Massy-Palaiseau par exemple, où j'ai quatre itinéraires possibles pour rentrer chez moi (3 bus et 1 RER) et que ce qui m'intéresse c'est le premier qui part... 


Merci encore ! 

Le code de la v3 est déjà dispo quelque part (même si elle est pas finie)? Je prendrais bien un peu d'avance pour l'étudier... 


----- Mail original -----

De: "Pierre Grimaud" <notifications@github.com> 
À: "pgrimaud/horaires-ratp-api" <horaires-ratp-api@noreply.github.com> 
Cc: "Nicolas Derive" <kalon33@ubuntu.com>, "Mention" <mention@noreply.github.com> 
Envoyé: Vendredi 10 Février 2017 13:25:29 
Objet: Re: [pgrimaud/horaires-ratp-api] Erreur récupération horaires sur Bus 21 (#41) 



Pas de soucis 😄 . Oui, le trafic des bus est prévu dans la v3, ainsi que le trafic du RER C, D, E et transilien. 

Tu as la liste des destinations ici : https://api-ratp.pierre-grimaud.fr/v2/bus/21 
https://api-ratp.pierre-grimaud.fr/v2/bus/21/stations/gare+saint+lazare?destination=porte+de+gentilly 


Les slugs ne sont pas les mêmes entre les destinations et stations. (Je me suis basé sur ceux proposés par la RATP...). Mais tout ça sera normalisé dans la v3. 

(v3 disponible dans moins de 10 jours. #teasing)

**Comment by pgrimaud** [comment]
Malheureusement, pas de code encore :/

La v3 sera une release **complète** du code source de l'API. Jusqu'à présent, je ne pouvais pas pour des raisons légales.

De plus j'ai développé un SDK pour utiliser la nouvelle API SOAP de la RATP qui a été ouverte au public au début de l'année. (https://data.ratp.fr/explore/dataset/horaires-temps-reel/)

Pour l'instant j'ai juste prévu de publier le code la v2, en le modifiant pour y intégrer ce SDK comme data provider. Du coup il sera parfaitement envisageable d'ajouter des features, comme les horaires de toutes les lignes à un arrêt spécifique.
