### ISSUE TITLE
RER E : Resource not found

### ISSUE THREAD

**Issue by user5885** [pgrimaud/horaires-ratp-api#46]
Bonsoir, je permet de demander un éclaircissement concernant la ligne RER E.
Tout d'abord j'appelle:
```
GET https://api-ratp.pierre-grimaud.fr/v3/lines/rers/E
```
qui me renvoie
```
"result": [
    {
      "code": "E",
      "name": "RER E",
      "directions": "Chelles Gournay-Tournan / Haussmann Saint Lazare",
      "id": "264000"
    }
  ]
```
chose étrange, car il y a bien 3 terminus sur l'ensemble de la ligne
puis je souhaite connaitre les destinations de cette ligne:
```
GET https://api-ratp.pierre-grimaud.fr/v3/destinations/rers/E?id=264000
```
la réponse suivante est déconcertante, car Chelles Gournay n'est pas situé au même endroit que Tournan
```
"result": {
    "destinations": [
      {
        "name": "Chelles Gournay / Tournan",
        "way": "A"
      },
      {
        "name": "Haussmann-Saint-Lazare / Gare de l'Est",
        "way": "R"
      }
    ]
  }
```
par conséquent si j'essaye:
```
https://api-ratp.pierre-grimaud.fr/v3/schedules/rers/E?id=264000/pantin/A
```
l'API me retourne Resource Not Found:
```
"result": {
    "code": 404,
    "message": "Resource not found"
  }
```
Peut-être ai-je mal compris comment est organisée cette ligne...

**Comment by pgrimaud** [comment]
Bonjour,

Les paramètres GET doivent toujours se placer en fin de requête. Par conséquent, la requête valide est la suivante : 

```
https://api-ratp.pierre-grimaud.fr/v3/schedules/rers/E/pantin/A?id=264000
```

Le RER E semble être mal géré du côté de la RATP. (1 seule ligne, et pas d'horaires...)

**Comment by user5885** [comment]
J'aurai espéré un système plus abouti de la part d'une grande entreprise tel que la RATP.

**Comment by user5885** [comment]
Désolé de vous embetter mais, pour le RER A
la requête suivante fonctionne:
```
GET https://api-ratp.pierre-grimaud.fr/v3/schedules/rers/A/gare+de+lyon/A
```
mais quand je specifie l'id de la ligne, j'obtiens une réponse similaire au cas du RER C, D et E (pas d'horaires, juste la destination):
```
GET https://api-ratp.pierre-grimaud.fr/v3/schedules/rers/A/gare+de+lyon/A?id=77
```

**Comment by user5885** [comment]
Même cas que pour #47, le paramètre ID doit être spécifié en majuscule:
ainsi ceci renvoie le résultat attendu:
```
https://api-ratp.pierre-grimaud.fr/v3/schedules/rers/A/gare+de+lyon/A?ID=77
```
en revanche pas d'horaires en appellant:
```
https://api-ratp.pierre-grimaud.fr/v3/schedules/rers/A/gare+de+lyon/A?id=77
```

**Comment by pgrimaud** [comment]
Je vais regarder ça demain. Pourtant le paramètre `id ` doit bien être passé en **minuscule**.

**Comment by pgrimaud** [comment]
Après investigation, les horaires des RER C, D et E ne sont pas renvoyés depuis l'API officielle RATP... 

Elle me renvoie l'erreur suivante : 

```
Les informations horaires ne sont pas disponibles pour le moment.
Veuillez nous excuser pour la gêne occasionnée.
```
