### ISSUE TITLE
Schedules Métros 3b et 7b : Ambiguous line

### ISSUE THREAD

**Issue by user5885** [pgrimaud/horaires-ratp-api#47]
```
GET https://api-ratp.pierre-grimaud.fr/v3/schedules/metros/3b/gambetta/A
GET https://api-ratp.pierre-grimaud.fr/v3/schedules/metros/7b/danube/A
```
Réponse:
```
"result": {
    "code": 400,
    "message": "Ambiguous Line"
  }
```
si l'id de la ligne spécifié, renvoie uniquement la destination.

**Comment by user5885** [comment]
Autant pour moi, la lettre doit être spécifiée en majuscule comme ça:
```
https://api-ratp.pierre-grimaud.fr/v3/schedules/metros/3B/gambetta/A
```

**Comment by pgrimaud** [comment]
Merci pour le retour @user5885 !

Je vais faire en sorte que 
```
https://api-ratp.pierre-grimaud.fr/v3/schedules/metros/3b/gambetta/A
```
et
```
https://api-ratp.pierre-grimaud.fr/v3/schedules/metros/3B/gambetta/A
```
aient le même comportement.

Et je vais regarder le problème du paramètre ID, reporté sur le #46 .

**Comment by pgrimaud** [comment]
Corrigé via https://github.com/pgrimaud/ratp-api-rest/commit/e089736c191fc42365aaba1f9289d0906350fa8e
