### ISSUE TITLE
Need coordinates for station

### ISSUE THREAD

**Issue by teressaeid** [pgrimaud/horaires-ratp-api#48]
Si il serait possible d'avoir les coordonnées géographiques des stations pour les positionner sur une carte, on pourrait par exemple les mettre sous format:

        "position": {
            "lat" : 48.86567809641779,
            "long": 2.321193771801867
        }

ou lat et long sont de type double.

Merci encore ^_^

**Comment by fabifabi** [comment]
meme demande :)

**Comment by pgrimaud** [comment]
Bonjour,

Malheureusement l'API officielle RATP ne renvoie pas cette information dans la liste des stations.

Aucun moyen de récupérer toutes les stations d'une lignes avec leurs coordonnées en 1 seul appel.

Il est seulement possible de récupérer les coordonnées d'une station via une recherche par GeoPoint, qui ne renvoie que... **la station la plus proche de CHAQUE ligne**. 

 Est-ce que c'est intéressant pour vous ? @teressaeid @fabifabi
