### ISSUE TITLE
merci !

### ISSUE THREAD

**Issue by ludovicgrimbert** [pgrimaud/horaires-ratp-api#50]
grâce à vous, j'ai pu faire cette app sur ios en swift, https://itunes.apple.com/us/app/transparis-horaires-temps-r%C3%A9el-ratp/id1229183952?l=fr&ls=1&mt=8

Amicalement,
ludovic

**Comment by pgrimaud** [comment]
Hello @ludovicgrimbert ! De rien ! Ça fait plaisir de voir que l'API sert aux gens.
 
Félicitations ! L'app est claire et fait bien ce qu'on lui demande.

**Comment by ludovicgrimbert** [comment]
Encore merci d'avoir créer l'API :)
Je vais prochainement faire une maj pour rajouter de la précision sur la
destination des horaires RER car La je pêche un peu ... mais après mon app
sera parfaite ( hohoho )

Le jeu. 15 juin 2017 à 15:25, Pierre Grimaud <notifications@github.com> a
écrit :
