### ISSUE TITLE
Problème info trafic?

### ISSUE THREAD

**Issue by hodd** [pgrimaud/horaires-ratp-api#51]
Bonjour, je viens de voir qu'il n'y avait pas toujours l'info exacte du trafic (exemple, lors de mon test à 13h54 les informations envoyées par votre API ne correspondent pas à celles affichées sur le site ratp).  Est-ce que votre API trafic effectue bien l'appel en temps réel à chaque fois, ou y a-t-il un système de cache? Merci

**Comment by pgrimaud** [comment]
Bonjour @hodd 

En effet, le traffic est KO depuis la maj de la semaine dernière du site de la RATP.
J'essaie de réparer ASAP.

ref : https://github.com/pgrimaud/ratp-api-rest/issues/3

**Comment by pgrimaud** [comment]
@hodd C'est corrigé, dis moi si c'est ok pour toi.

**Comment by hodd** [comment]
C'est parfait, merci !

**Comment by guidugui** [comment]
Bonjour,
Il est 18h54, et lorsque je fais une requête "https://api-ratp.pierre-grimaud.fr/v3/traffic", j'ai par exemple sur la ligne 3 un incident ayant eu lieu à 13h59, alors que cet incident est terminé actuellement et que le site RATP ne l'affiche plus. De même sur le RER B et le T1, l'API affiche encore des incidents étant terminés depuis plusieurs heures.
Subsiste-t-il toujours un bug sur l'API trafic ?
Merci. Et bravo cet api est génial !!

**Comment by pgrimaud** [comment]
@guidugui Merci du retour.

Je viens de pousser un autre correctif : https://github.com/pgrimaud/ratp-api-rest/commit/dff1404a958bf131f9f0a3d1495bdc38a13b5937

Les données restaient en cache du côté de la RATP.

À suivre dans les jours à venir si ça marche bien.

**Comment by guidugui** [comment]
Super, merci beaucoup. Bonne soirée.

**Comment by pgrimaud** [comment]
@guidugui Je viens de vérifier, c'est corrigé et opérationnel.
Merci encore

**Comment by guidugui** [comment]
Oui, j'ai regardé sur un incident sur la ligne 6 ce soir et en effet ça a l'air de bien fonctionner. Super boulot, merci encore :)
