### ISSUE TITLE
Trafic : "slug" sur incident et quand il y a des travaux

### ISSUE THREAD

**Issue by guidugui** [pgrimaud/horaires-ratp-api#52]
Bonjour,
Dans le trafic, lorsqu'il est normal et qu'il y a des travaux, le slug de la ligne en question prend la valeur "normal_trav". Or, sur incident, le slug prend les valeurs "alerte" ou "critique" mais du coup il n'y a plus moyen de savoir s'il y a des travaux en même temps ou pas. Serait-il possible de prévoir deux valeurs en plus : "alerte_trav" et "critique_trav" par exemple (mais laisser la rubrique title tel qu'elle, c'est à dire "Trafic perturbé" ou "Trafic très perturbé") ?
Ce qui permettrait, par exemple, d'afficher un pictogramme orange ou rouge avec en plus le petit symbole de travaux sur un application ;)

Merci.

**Comment by pgrimaud** [comment]
Bonjour,

Du côté de la RATP, l'information alerte ou critique semble prendre le dessus sur les travaux. Donc impossible d'avoir les deux informations en même temps.

**Comment by guidugui** [comment]
Ah mince, dommage. Reste plus qu'a trouver le développeur à la RATP ;)

Merci encore, bonne soirée.
