### ISSUE TITLE
Destinations

### ISSUE THREAD

**Issue by stewartjim** [pgrimaud/horaires-ratp-api#53]
Bonjour,

Merci beaucoup pour cet API très utile.

Serait-il possible que la destination soit "réelle" pour intégrer :
- les lignes qui ont des branches (Métro 13, RER B)
- les services partiels (bus, ...)
Ce serait un vrai plus.

Merci par avance

**Comment by pgrimaud** [comment]
Bonjour,

Je viens de publier un correctif au niveau des lignes avec des branches.
Exemple :

```
GET https://api-ratp.pierre-grimaud.fr/v3/schedules/metros/13/saint+lazare/A
```

```
{  
   "result":{  
      "schedules":[  
         {  
            "message":"Train a quai",
            "destination":"Saint-Denis-Universite"
         },
         {  
            "message":"Train retarde",
            "destination":"Asnieres-Gennevilliers Les Courtilles"
         },
         {  
            "message":"Train retarde",
            "destination":"Saint-Denis-Universite"
         },
         {  
            "message":"Train retarde",
            "destination":"Asnieres-Gennevilliers Les Courtilles"
         }
      ]
   },
   "_metadata":{  
      "call":"GET /schedules/metros/13/saint+lazare/A",
      "date":"2017-10-11T15:48:57+02:00",
      "version":3
   }
}
```

Qu'entendez-vous par services partiels ?

Bonne journée

**Comment by stewartjim** [comment]
Bonsoir,

Merci pour les modifications.
Depuis cette mise à jour, j'ai l'impression que certaines lignes de bus sont en erreur 500 : exemple PC1 
https://api-ratp.pierre-grimaud.fr/v3/schedules/bus/PC1/porte+de+champerret/R

Quand je disais service partiel, j'entendais certaines lignes de bus qui peuvent :
- Ponctuellement avoir un terminus intermédiaire suite à un incident de circulation
- Structurellement ont un terminus en milieu de parcours (branche ou non). (Exemple : bus 38 jusqu'à Chatelet au lieu de gare du Nord).
Ce sont des informations cruciales pour l'utilisateur.

Merci

**Comment by pgrimaud** [comment]
Bonsoir,

Je viens de corriger les erreurs 500 sur les bus.
Les destinations sont désormais exactes, je pense que le service partiel est donc pris en compte sur chaque ligne.

Bonne soirée

**Comment by stewartjim** [comment]
Bonjour, 
Tout est parfait. Merci beaucoup !
Bonne journée.

**Comment by stewartjim** [comment]
Bonjour, depuis ce matin. Les destinations sont devenues "théoriques" et ne prennent pas en compte les différentes branches (exemple sur la ligne 13 : https://api-ratp.pierre-grimaud.fr/v3/schedules/metros/13/saint+lazare/A). Bonne journée.
