### ISSUE TITLE
Mission code and destination not displayed for RER B

### ISSUE THREAD

**Issue by kalon33** [pgrimaud/horaires-ratp-api#55]
Using prototype RATP next departures screen (ecran-ratp) last version, I don't get mission codes and destination anymore, but a vague direction information for RER B line (example [here](http://ratp.spiralo.net/ecran/)).

Is this possible to fix this?

Thanks for your help.

**Comment by pgrimaud** [comment]
Hi @kalon33, I just fixed it : https://github.com/pgrimaud/horaires-ratp-api/commit/e22df13952f21fa24a5cfbb0b2c86fc8aab71816

Regards

**Comment by kalon33** [comment]
Hi @pgrimaud, thanks a lot! 

Regards 

----- Mail original -----

De: "Pierre Grimaud" <notifications@github.com> 
À: "pgrimaud/horaires-ratp-api" <horaires-ratp-api@noreply.github.com> 
Cc: "Nicolas Derive" <kalon33@ubuntu.com>, "Mention" <mention@noreply.github.com> 
Envoyé: Lundi 16 Octobre 2017 10:43:19 
Objet: Re: [pgrimaud/horaires-ratp-api] Mission code and destination not displayed for RER B (#55) 



Hi @kalon33 , I just fixed it : e22df13 


Regards
