### ISSUE TITLE
Ambiguous Line for any station on Tram T3A

### ISSUE THREAD

**Issue by rrnjeim** [pgrimaud/horaires-ratp-api#57]
Hello Pierre,
Merci pour l'API avant tout!

In this V3 version, the Tramway T3A doesn't seem to work properly, for me at least. I tried all possible combinations in the URL (uppercase, lowercase, name, slug.. ) in vain. 
Her's what I'm looking for-->
https://api-ratp.pierre-grimaud.fr/v3/schedules/tramways/3A/montsouris/A

Am I missing something ??

Thank you in advance,
Ralph

**Comment by bladx** [comment]
Salut Ralph,

Je pense qu'il te suffit de mettre le 'a' de 3A en minuscule : https://api-ratp.pierre-grimaud.fr/v3/schedules/tramways/3a/montsouris/A

Xavier

**Comment by rrnjeim** [comment]
Salut Xavier!

j'avais pensé a tout sauf à ca! Finalement ca marche bien, merci mec ;)

Ralph
