### ISSUE TITLE
Some routes seem to be down

### ISSUE THREAD

**Issue by bladx** [pgrimaud/horaires-ratp-api#58]
Hello,

Firstly thank you very much for converting SOAP RATP to REST, that's so useful.
Anyway, since this morning all the routes of the kind: 
https://api-ratp.pierre-grimaud.fr/v3/schedules/rers/b/massy-palaiseau/A
seem to respond a 500 error.

While https://api-ratp.pierre-grimaud.fr/v3/traffic does work like a charm.

Do you know why ?

Best Regards from Paris,

Xavier

**Comment by pgrimaud** [comment]
Hello @bladx,

I just received this email :
<img width="583" alt="opendata" src="https://user-images.githubusercontent.com/1866496/28922347-1306c2e0-785a-11e7-96bf-ad1fe00bb96c.png">

I can't fix it, we have to wait for a fix from the official RATP API.

Pierre

**Comment by bladx** [comment]
Thank you Pierre.
It's UP again :)
