### ISSUE TITLE
Détails d'une misssion

### ISSUE THREAD

**Issue by TienHai** [pgrimaud/horaires-ratp-api#59]
Bonjour et merci de l'API,

J'essaie de me faire une petite application sur le trafic de la ratp, donc super je trouve cette api. J'arrive a obtenir les horaires de passage a une gare donnée, parfait.

Par contre est-il possible de :
 - obtenir les info sur une mission ? savoir ou il est ? savoir quelle gare sont desservie par ce train ?
 - peut on savoir les correspondances d'une ligne ?

Merci,

Tien Haï

**Comment by pgrimaud** [comment]
Bonjour,

> obtenir les info sur une mission ? 
> savoir ou il est ? 

Malheureusement l'API RATP ne permet pas de récupérer les informations des missions.

> savoir quelle gare sont desservie par ce train ?

Idem. Mais c'est possible en se basant sur le code de la mission. Par exemple : https://rera-leblog.fr/les-codes-missions-des-rer-a-dechiffres/

> peut on savoir les correspondances d'une ligne ?

Idem.

En bref, pas grand chose n'est disponible, désolé. 😞

**Comment by pgrimaud** [comment]
@TienHai Je viens de voir que la WSDL de l'API SOAP de la RATP a été mise à jour. Il semblerait que le détail des missions soit disponible. Je regarde et je te fais un retour.

**Comment by pgrimaud** [comment]
@TienHai Les seuls informations que je peux avoir d'une mission, sont les stations, et cela ne fonctionne que pour les RERs.

Example : 
https://api-ratp.pierre-grimaud.fr/v3/mission/rers/A/ZEMA

**Comment by TienHai** [comment]
Super !!! Merci.
