### ISSUE TITLE
Code serveur

### ISSUE THREAD

**Issue by Phyks** [pgrimaud/horaires-ratp-api#6]
Bonjour,

J'aimerais beaucoup utiliser un service de ce genre hébergé sur mon serveur pour me fournir les données. Est-il possible d'avoir plus d'informations sur le code côté serveur ? Est-il prévu de le diffuser ?

Merci

**Comment by princeN** [comment]
Bonjour,
Je suis également interessé. Sur quelle API RATP cette API se base-t-elle en premier lieu? La RATP n'ouvre ses données qu'au compte goute et sauf à parser leur page horaire, je n'ai jamais trouvé de solution. 
Merci

**Comment by bbouabou** [comment]
Je pense qu'il a du utiliser wireshark sur une des applis ratp ( par exemple celle d'android)  pour scanner les paquets emis entre le client et le serveur.  Ensuite suffit de reproduire le même comportement pour avoir les bonnes datas en live.

**Comment by pgrimaud** [comment]
Hello,

Je préfère ne pas divulger le code serveur, vu qu'il s'agit d'un simple scraping du site de la RATP via des proxys et que c'est contre les TOS du site. Je pars de ces pages regarder ces pages http://www.ratp.fr/horaires/fr/ratp/metro et http://www.ratp.fr/horaires/fr/ratp/rer

**Comment by princeN** [comment]
C'est ce que je pensais, merci pour la réponse et surtout pour la mise en place de l'API! Par contre j'aimerai faire un appel qui me renvoit les arrêts desservis afin de déterminer qu'un RER est omnibus ou non. 
La limite de 30 sec rend ceci plus complexe si on veut avoir le résultat immédiatement. Une idée sur la solution à retenir?

**Comment by pgrimaud** [comment]
@princeN Hmmm je dirais de repérer les "codes missions" des trains et de faire des appels à l'API sur une station qui est déservie par tous les trains comme Denfert ou Châtelet et dans les deux sens de circulation.

Les codes missions sont en gros :
A*** = GARE DU NORD
E*** = AEROPORT DE ROISSY CDG 2 TGV
G*** = AULNAY-SOUS-BOIS
I*** = MITRY-CLAYE
J*** = DENFERT-ROCHEREAU
K*** = MASSY-PALAISEAU
L*** = ORSAY-VILLE
P*** = SAINT-REMY-LES-CHEVREUSE
Q*** = LA PLAINE-STADE DE FRANCE
S*** = ROBINSON
U*** = LAPLACE

Il suffit juste de lister les arrêts déservis par trains en fonction des missions et avec ça y'a moyen de savoir à quelles station le train s'arrête.

**Comment by princeN** [comment]
@pgrimaud Merci pour l'info sur les codes missions, j'ai trouvé mon bonheur et je vais ajouter un contrôle js sans surchager l'API, tant mieux.

**Comment by fwininger** [comment]
@pgrimaud : c'est quoi ce dépot qui donne même pas le code source de son api ? Il serait bien de mettre ton code serveur en opensource.

**Comment by pgrimaud** [comment]
@fwininger Bonjour déjà. Parce qu'ouvrir des données privées est à la limite de la légalité, si je mets les sources c'est la fermeture du repo direct. Si t'es pas un dev en carton, tu peux le faire en 30 minutes. :goat:

**Comment by Phyks** [comment]
@fwininger À noter qu'il existe https://github.com/ksahnine/trafic-ratp-dropwizard qui lui diffuse ses sources.

**Comment by fwininger** [comment]
@Phyks : Merci pour le dépot :+1: 
@pgrimaud : je ne pense pas que tu as compris l'utilité et la philosophie de l'open-source => un dépôt github ce n'est pas un readme d'API. Mais passons.

**Comment by leoetlino** [comment]
@fwininger Je viens de publier [une API](https://github.com/leoetlino/ratp-api) qui ne s'appuie pas sur le web scraping, mais sur l'API utilisée par l'appli RATP officielle sur Android.

Puisque c'est self-hosted, ça permet d'éviter de surcharger un seul serveur API, et surtout, de ne pas être dépendant sur un seul service (que la RATP pourrait demander à fermer).

**Comment by fwininger** [comment]
@leoetlino pas mal, j'ai également réalisé le sniffing de l'API de l'application Android pour récupérer les JSON que j'avais besoin. Je pense qu'il serait intéressant de publier les spefications de l'API apixha.ixxi.net. Il est toujours plus intéressant d'utiliser les données primaires.

**Comment by leoetlino** [comment]
Oui, une page consacrée à l'API officielle pourrait être assez utile. Pour commencer, il y a déjà une page de débogage qui liste les API disponibles ([apixha.ixxi.net/APIX](http://apixha.ixxi.net/APIX)).
