### ISSUE TITLE
Error de la destination pour le RER A

### ISSUE THREAD

**Issue by TienHai** [pgrimaud/horaires-ratp-api#60]
Bonjour,

Dans la requête pour les destination du RER A j'ai comme response : 

        "destinations": [
            {
                "name": "Marne-la-Vallee Chessy / Boissy-Saint-Leger",
                "way": "A"
            },
            {
                "name": "Cergy-Le-Haut / Poissy / Saint-Germain-en-Laye",
                "way": "R"
            }
        ]

Par contre quand je demande les horaires de la ligne A pour une station avec comme way = A : 

        "schedules": [
            {
                "code": "TEDI",
                "message": "09:49",
                "destination": "St-Germain-en-Laye. Poissy. Cergy."
            },
            {
                "code": "UBOS",
                "message": "09:46",
                "destination": "St-Germain-en-Laye. Poissy. Cergy."
            },
            ...
        ]
       
        "_metadata": {
            "call": "GET /schedules/rers/a/noisiel/A",
            "date": "2017-09-15T09:44:47+02:00",
            "version": 3
        }

Il y a une inversion de dans le "name" dans la requête de "destinations"

Merci,

**Comment by pgrimaud** [comment]
Hello @TienHai ,

Comme répondu sur les autres issues, c'est corrigé.

```
GET https://api-ratp.pierre-grimaud.fr/v3/schedules/rers/a/grande+arche+la+defense/A
```
Retourne maintenant :
```
{  
   "result":{  
      "schedules":[  
         {  
            "code":"TROC",
            "message":"Train Ã  quai V.2",
            "destination":"Poissy"
         },
         {  
            "code":"UDON",
            "message":"16:00 Voie 2",
            "destination":"Cergy-Le-Haut"
         },
         {  
            "code":"ZEUS",
            "message":"16:03 Voie 2",
            "destination":"Saint-Germain-en-Laye"
         },
         {  
            "code":"TROC",
            "message":"16:05 Voie 2",
            "destination":"Poissy"
         },
         {  
            "code":"URUS",
            "message":"16:08 Voie 2",
            "destination":"Cergy-Le-Haut"
         },
         {  
            "code":"ZEUS",
            "message":"16:11 Voie 2",
            "destination":"Saint-Germain-en-Laye"
         }
      ]
   },
   "_metadata":{  
      "call":"GET /schedules/rers/a/grande+arche+la+defense/A",
      "date":"2017-10-11T15:52:44+02:00",
      "version":3
   }
}
```
