### ISSUE TITLE
Ambiguous line T3a

### ISSUE THREAD

**Issue by chocomega** [pgrimaud/horaires-ratp-api#61]
Bonjour la requête suivante ne fonctionne plus depuis hier soir et renvoie "Ambiguous Line":
https://api-ratp.pierre-grimaud.fr/v3/schedules/tramways/3a/Poterne%20des%20Peupliers/R

Meme résultat avec le slug au lieu du nom de la station:
https://api-ratp.pierre-grimaud.fr/v3/schedules/tramways/3a/poterne+des+peupliers/R

En ajoutant l'id, le résultat est incorrect avec la destination dupliquée une centaine de fois:
https://api-ratp.pierre-grimaud.fr/v3/schedules/tramways/3a/Poterne%20des%20Peupliers/R?id=198721

```{
    "result": {
        "schedules": [
            {
                "destination": "Pont du Garigliano"
            },
            {
                "destination": "Pont du Garigliano"
            },
...

**Comment by pgrimaud** [comment]
@chocomega Merci du retour, c'est corrigé

**Comment by chocomega** [comment]
Excellent ! Merci pour votre service et réactivité.
