### ISSUE TITLE
Ambiguous Line

### ISSUE THREAD

**Issue by vincentraulic** [pgrimaud/horaires-ratp-api#63]
Bonjour,

Cette issue pour un problème que je rencontre avec la ligne D : 

Ambiguous Line pour lister les stations de la D (j'ai du utiliser l'id 213760)
https://api-ratp.pierre-grimaud.fr/v3/stations/rers/d

PS : J'ai également un Schedules unavailable sur cette ligne quelle que soit la station que j'ai utilisé https://api-ratp.pierre-grimaud.fr/v3/schedules/rers/d/stade+de+france+saint+denis/A?id=213760

Cordialement,

**Comment by pgrimaud** [comment]
Bonjour,

Les RER C et D sont gérés par la SNCF, et ne sont pas bien implémentés du côté de la RATP... Je ne peux rien faire malheureusement. 😞
