### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by chocomega** [pgrimaud/horaires-ratp-api#64]
https://api-ratp.pierre-grimaud.fr/v3/ renvoie l'erreur suivante :
ERR_CONNECTION_TIMED_OUT

**Comment by Pierre-Saigot** [comment]
C'est normal, don't panic, sûrement du à cause d'un problème chez OVH https://twitter.com/olesovhcom/status/928521489426632705

**Comment by chocomega** [comment]
Ah merci pour l'info !

**Comment by pgrimaud** [comment]
Exact @Pierre-Saigot , c'est revenu @chocomega .
