### ISSUE TITLE
Schedules RER C

### ISSUE THREAD

**Issue by florianmopin** [pgrimaud/horaires-ratp-api#65]
Bonjour,

Tout d'abord merci pour cette api, elle m'est bien utile pour un projet. Cependant je rencontre une difficulté quand j'essaie de récupérer les horaires du rer C à la station Pont du Garigliano.
 
`https://api-ratp.pierre-grimaud.fr/v3/schedules/rers/c/pont+garigliano/A+R`

J'obtiens une erreur 400.

**Comment by florianmopin** [comment]
Je viens de voir sur le readme que les RER C ne marchait pas.

**Comment by pgrimaud** [comment]
Hello,

Ouais c'est très mal foutu pour les RER C / D et E. Désolé de ne pas pouvoir t'aider.
