### ISSUE TITLE
Apostrophe dans les slugs de stations

### ISSUE THREAD

**Issue by cpa** [pgrimaud/horaires-ratp-api#66]
La première station du T4 est
```
{
    "slug": "gare+d'aulnay+sous+bois",
    "name": "Gare d'Aulnay Sous Bois"
}
```
(d'après https://api-ratp.pierre-grimaud.fr/v3/stations/tramways/4).

Or un appel à https://api-ratp.pierre-grimaud.fr/v3/schedules/tramways/4/gare+d'aulnay+sous+bois/A+R
renvoie une erreur 500, probablement à cause de l'apostrophe.

J'ai essayé en supprimant l'apostrophe et en la remplaçant par +, mais erreur 500 toujours.

Et j'en profite pour te remercier pour cette API très très pratique !

**Comment by pgrimaud** [comment]
Bonjour,

Merci pour le retour, j'ai corrigé l'erreur 500.

Après investigation, je viens de voir que le T4 n'était pas géré par la RATP mais par la SNCF. 
Tout comme le RER C, D et E, les horaires ne fonctionnent malheureusement pas. (Mauvaise récupération des informations de la RATP depuis l'API SNCF ?)

J'ai forcé la direction en passant le paramètre id et voici ce que l'API RATP renvoie : https://api-ratp.pierre-grimaud.fr/v3/schedules/tramways/4/gare+de+gargan/A?id=39837

Désolé et bonne soirée
