### ISSUE TITLE
Schedules bus 486

### ISSUE THREAD

**Issue by julien290** [pgrimaud/horaires-ratp-api#67]
Bonjour et merci pour cette API,

J'ai un problème quand je veux récupérer les schedules du bus 486, j'ai une erreur 400 notamment avec cet url:
https://api-ratp.pierre-grimaud.fr/v3/schedules/bus/486/buisson/A+R

Ai-je oublié quelque chose ?
Merci d'avance.

**Comment by pgrimaud** [comment]
Bonjour,

Non, vous avez tout bon dans la configuration de l'url.

Il semblerait que la RATP ne gère pas bien les données des lignes qui ne lui sont pas propres. Comme les RER C, D et E qui sont gérés par la SNCF. Après quelques recherches, il semblerait que ce soit Keolis qui gère la ligne 486, d'où cette erreur. 

Malheureusement, je ne sais pas comment régler ce problème pour le moment.

**Comment by julien290** [comment]
Mince..

Merci pour les explications en tout cas, en espérant une meilleure gestion de la pars de la RATP dans les prochaines versions de leur API.

Merci quand même !
