### ISSUE TITLE
Error on Directions 

### ISSUE THREAD

**Issue by Bubbles2** [pgrimaud/horaires-ratp-api#68]
Hi 
I would be grateful if you could help me with the following problem.
If I check the destinations for  Bus 86 I get the following

"result": {
        "destinations": [
            {
                "name": "Saint-Mande - Demi Lune - Parc Zoologique",
                "way": "A"
            },
            {
                "name": "Saint-Germain-Des-Pres",
                "way": "R"
            }

So the way for direction  "Saint-Germain-Des-Pres should be R

but if I use  https://api-ratp.pierre-grimaud.fr/v3/schedules/bus/86/eglise+de+saint+mande/R

Note the destination is "Saint-Mande - Demi Lune - Parc Zoologique" so the way is wrong 

{
    "result": {
        "schedules": [
            {
                "message": "3 mn",
                "destination": "Saint-Mande - Demi Lune - Parc Zoologique"
            },
            {
                "message": "24 mn",
                "destination": "Saint-Mande - Demi Lune - Parc Zoologique"
            }
        ]
    },
    "_metadata": {
        "call": "GET /schedules/bus/86/eglise+de+saint+mande/R",
        "date": "2018-02-08T22:38:47+01:00",
        "version": 3
    }
}

**Comment by pgrimaud** [comment]
Hi,

I'm gonna check this asap. Thanks for the issue.

**Comment by pgrimaud** [comment]
Hi @Bubbles2,

Unfortunately, this data are returned by the official RATP API.
I contact them about it. Wait and see.
