### ISSUE TITLE
Fonctionnalité geolocalisation RATP

### ISSUE THREAD

**Issue by wajisan** [pgrimaud/horaires-ratp-api#69]
Bonjour,
Tout d'abord bravo et merci pour cette API, bien documentée et efficace.

Je commence à l'utiliser et je me demandais si avec la geolocalisation (lattitude, longitude) il était possible de récupérer les stations (bus, metro...) les plus proches dans un rayon donnée (en JSON).

Je ne pense l'avoir pas vu dans l'API et cela pourrait être une fonctionnalité intéressante.
Je serais heureux de savoir comment m'y prendre, si cela existe sur l'API RATP,

Bien cordialement et merci !

**Comment by pgrimaud** [comment]
Bonjour,

Malheureusement l'API officielle RATP ne renvoie pas cette information dans la liste des stations.

Aucun moyen de récupérer toutes les stations d'une lignes avec leurs coordonnées en 1 seul appel.

Il est seulement possible de récupérer les coordonnées d'une station via une recherche par GeoPoint, qui ne renvoie que... la station la plus proche de CHAQUE ligne.

**Comment by wajisan** [comment]
D'accord, merci pour la réponse et sa rapidité.
