### ISSUE TITLE
Problème ligne RER C

### ISSUE THREAD

**Issue by ninjax95** [pgrimaud/horaires-ratp-api#77]
Bonjour ,

Je souhaiterais récupérer les informations de la ligne de RER C de même pour le D. 
https://api-ratp.pierre-grimaud.fr/v3/stations/rers/c

Mais j'ai le code suivant : 
{
    "result": {
        "code": 400,
        "message": "Ambiguous Line"
    },
    "_metadata": {
        "call": "GET /stations/rers/c",
        "date": "2018-05-22T08:13:11+02:00",
        "version": 3
    }
}

Est-ce un rapport avec le bug que vous signalez ? Sera-t-il résolu ?

Merci

**Comment by pgrimaud** [comment]
Hello @ninjax95,
Malheureusement oui, c'est le même problème que pour le RER D.
Aucune idée si cela sera résolu prochainement...
