### ISSUE TITLE
Problème de destination

### ISSUE THREAD

**Issue by mehdicopter** [pgrimaud/horaires-ratp-api#78]
Bonjour !
Je veux les temps de passage pour le T2 direction Porte de Versailles à Jacqueline Auriol.
Le JSON pour le code des directions est le suivant :

`{
    "result": {
        "destinations": [
            {
                "name": "Porte de Versailles",
                "way": "A"
            },
            {
                "name": "Pont de Bezons",
                "way": "R"
            }
        ]
    },
    "_metadata": {
        "call": "GET /destinations/tramways/2",
        "date": "2018-08-25T21:38:12+02:00",
        "version": 3
    }
}`

Donc l'url finale est : [https://api-ratp.pierre-grimaud.fr/v3/schedules/tramways/2/jacqueline+auriol/A](url) 
Or voici le JSON :

`{
    "result": {
        "schedules": [
            {
                "message": "5 mn",
                "destination": "Pont de Bezons"
            },
            {
                "message": "19 mn",
                "destination": "Pont de Bezons"
            }
        ]
    },
    "_metadata": {
        "call": "GET /schedules/tramways/2/jacqueline+auriol/A",
        "date": "2018-08-25T21:38:03+02:00",
        "version": 3
    }
}`

La destination n'est pas la bonne...
Une petite correction s'impose :)
Merci d'avance et super boulot !

**Comment by ChadiEM** [comment]
C'est un [bug coté RATP](https://github.com/pgrimaud/ratp-api-rest/issues/5), si j'ai bien compris.

J'ai du faire un gros workaround en appelant les `schedules` en A et R sur les **terminus**, et déduire a partir de ces infos quel est le bon sens. Avec un fallback mode sur ce que l'API donne.

Regarde [comment](https://gist.github.com/ChadiEM/bc4014fa61f08b31f3d42a5e78c49d9b#file-ratp_utils-rb-L75) je l'ai fait pour les bus (et je viens de faire un fix d'ailleurs pour inclure les trams); pourtant moche, ça a l'air de marcher. ;-)

**Comment by mehdicopter** [comment]
Merci bro !
J'utilise justement ton widget smashing ;)
Très bon boulot btw !!
