### ISSUE TITLE
https certificate problem

### ISSUE THREAD

**Issue by djavan-bertrand** [pgrimaud/horaires-ratp-api#79]
When querying the api (or even https://api-ratp.pierre-grimaud.fr/v3/documentation), there is a security error.

<img width="853" alt="capture d ecran 2018-12-13 a 21 36 42" src="https://user-images.githubusercontent.com/630339/49966041-3b5fc000-ff1f-11e8-9fb8-26ef60fd17ac.png">

**Comment by pgrimaud** [comment]
The server which host the API was blacklisted by letsencryt 🙄

It's now fixed

**Comment by djavan-bertrand** [comment]
Thanks !
