### ISSUE TITLE
Récupérez les stations d'une gare

### ISSUE THREAD

**Issue by fsebbah** [pgrimaud/horaires-ratp-api#8]
Bonjour,
Je viens de découvrir votre API qui est très simple à utiliser.
Comment est-il possible d'obtenir la liste des stations d'une gare de métro ou de RER ?
Merci
Franck Sebbah

**Comment by pgrimaud** [comment]
Hello @fsebbah,
Je n'ai pas bien compris votre demande.
Vous souhaitez obtenir la liste des lignes à une station précise ?

**Comment by fsebbah** [comment]
Oui c'est exactement cela. Par exemple j'envoie RER B et je reçois la miste
des gares.
Merci
Franck
 Le 26 juin 2015 16:09, "Pierre Grimaud" <notifications@github.com> a
écrit :

**Comment by pgrimaud** [comment]
Par exemple : 
rer B : http://api-ratp.pierre-grimaud.fr/data/stations/rer/b
metro 8 : http://api-ratp.pierre-grimaud.fr/data/stations/metro/8

(Attention, pour rer ça ne renvoie que les gares gérées par la RATP)

**Comment by fsebbah** [comment]
Et allez sur le site transilien SNCF pour récupérer les autres stations ?
C'est beau le progrès. Mais les horaires sont bien ce des gares RATP ou
hors RATP ?
Merci pour vos réponses et votre temps.
Le 26 juin 2015 5:13 PM, "Pierre Grimaud" <notifications@github.com> a
écrit :

**Comment by pgrimaud** [comment]
@fsebbah Non je n'ai les stations de la SNCF, uniquement celles des gares gérées par la RATP (ces deux services sont indépendants).

Du coup, ce ne sont les horaires RATP.

**Comment by fsebbah** [comment]
Vive l'OpenData
Merci
