### ISSUE TITLE
[BUG] Something went wrong sur la route GET /traffic

### ISSUE THREAD

**Issue by bladx** [pgrimaud/horaires-ratp-api#82]
Bonjour Pierre,

Tout d'abord merci beaucoup pour cette API.
Sinon je voulais juste te signaler que depuis ce matin la route GET /traffic renvoie :
`{
    "result": {
        "message": "Something went wrong",
        "rers": [
            {
                "line": "C",
                "slug": "normal",
                "title": "Trafic normal",
                "message": "Trafic normal sur l'ensemble de la ligne."
            },
            {
                "line": "D",
                "slug": "normal",
                "title": "Trafic normal",
                "message": "Trafic normal sur l'ensemble de la ligne."
            },
            {
                "line": "E",
                "slug": "normal",
                "title": "Trafic normal",
                "message": "Trafic normal sur l'ensemble de la ligne."
            }
        ]
    },
    "_metadata": {
        "call": "GET /traffic",
        "date": "2019-04-05T13:25:15+02:00",
        "version": 3
    }
}`

Et par ailleurs, hier soir il y avait un problème sur la E et pourtant l'API renvoyait que tout allait bien sur cette ligne (je ne sais pas si c'est lié ?).

Aussi, saurais-tu pour quand la v4 est prévu ?

Bonne journée,

Xavier

**Comment by pgrimaud** [comment]
Bonjour,

Concernant le trafic, j'ai fait remonter l'information à la RATP.
Si je n'ai pas d'informations complémentaires de leur part d'ici 1 semaine, je mettrais en place une solution temporaire.

Je n'ai pas de deadline précise au sujet de la V4, malheureusement.

Bonne journée,

Pierre

**Comment by bladx** [comment]
Bonjour Pierre,

Je me doute que tu dois avoir d'autre sujets en parallèle.
Mais est-ce que tu as reçu une réponse de la part de la RATP ?

Bonne journée,

Xavier

**Comment by pgrimaud** [comment]
Hello @bladx, 

Oui, j'ai eu une réponse, mais pas de correctif en vue.
J'ai apporté un correctif temporaire pour rétablir le service.

Dis moi si tu vois quelque chose de louche.

Bonne journée,

Pierre

**Comment by eplanet** [comment]
C'est corrigé ! Merci. Par contre le résultat est différent : chaque ligne est un dictionnaire d'une seule clé correspondant au nom de la ligne, alors qu'avant les items de chaque ligne étaient directement dans le dictionnaire de la ligne. Cela va rester ainsi ?

**Comment by pgrimaud** [comment]
@eplanet Bien vu, merci. C'est corrigé : https://github.com/pgrimaud/ratp-api-rest/commit/d3ebb8f90679fa9c949a3f11d48841ec4202d06c.
