### ISSUE TITLE
Utf8 Encodage

### ISSUE THREAD

**Issue by sebyoga** [pgrimaud/horaires-ratp-api#84]
Bonjour,

Tout d'abord, un merci pour cette api qui fonctionne très bien et qui me sert pour ma domotique afin d'avoir un aperçu rapide de l'horaire des prochains passages de RER.

J'ai deux petites remarques néanmoins : 

- J'ai aléatoirement l'encodage du flux json renvoyé encodé bizarrement : Train Ã  quai (schedules/rers/A/station/A+R?_format=json), est-ce normal ? Comme c'est aléatoire, j'aurais tendance à penser que cela provient de l'api de la RATP ...

- Je n'arrive pas à obtenir de valeur pour l'état du traffic du RER A. Est-ce un soucis temporaire de l'API de la RATP ?

Je trouve cette API vraiment utile, et si vous avez besoin d'aide n'hésitez pas. (Je suis développeur web)

Avec mes remerciements,  
Sébastien

**Comment by pgrimaud** [comment]
Hello,

Je vais essayer de gérer le problème d'encodage dans la v4, qui devrait voir le jour le mois prochain. Merci pour le retour.

Pour l'état du traffic, je vais passer un correctif dans la journée.

Bonne journée,

Pierre

**Comment by pgrimaud** [comment]
@sebyoga FYI, L'information de traffic est de nouveau up.

**Comment by sebyoga** [comment]
@pgrimaud,

Un grand merci pour la rapidité. 

Je suis développeur Web Expert Drupal, si vous avez besoin d'un coup de main n'hésitez pas.

Bien à vous,

**Comment by pgrimaud** [comment]
Hello @sebyoga 

C'est corrigé sur la version 4 de l'API : 

https://api-ratp.pierre-grimaud.fr/v4/schedules/rers/A/nation/R

```

{
    "result": {
        "schedules": [
            {
                "code": "QUDO",
                "message": "Train à quai",
                "destination": "Marne-la-Vallee Chessy"
            },
            {
                "code": "NEMO",
                "message": "20:48",
                "destination": "Boissy-Saint-Leger"
            },
            {
                "code": "OPUS",
                "message": "20:57",
                "destination": "Torcy"
            },
            {
                "code": "QURE",
                "message": "21:08",
                "destination": "Marne-la-Vallee Chessy"
            },
            {
                "code": "NEMO",
                "message": "21:01",
                "destination": "Boissy-Saint-Leger"
            },
            {
                "code": "NEMO",
                "message": "21:16",
                "destination": "Boissy-Saint-Leger"
            }
        ]
    },
    "_metadata": {
        "call": "GET /schedules/rers/A/nation/R",
        "date": "2019-06-02T20:40:03+02:00",
        "version": 4
    }
}
```

**Comment by sebyoga** [comment]
Bonjour @pgrimaud,

Merci pour votre retour et votre action.

Bonne soirée,

Sébastien
