### ISSUE TITLE
[BUG] Pas d'informations sur certaines lignes

### ISSUE THREAD

**Issue by bladx** [pgrimaud/horaires-ratp-api#86]
Bonjour Pierre,

Je pense que cela date du fix que tu avais fait pour la route GET /traffic.
Ce matin il s'agissait du RER B, en ce moment de la ligne de métro 10 :
Nous n'avons pas suffisamment d'informations pour ces lignes.
Je pense que c'est quand il y a des soucis sur la ligne.
On a :
{
    "line": "10"
}
au lieu de (par exemple) :
{
    "line": "10",
    "slug": "issue",
    "title": "Problème sur la ligne",
    "message": "Problème en gare de XXX dû à un malaise voyageur."
}

Cordialement,

Xavier

**Comment by pgrimaud** [comment]
Hello,

Bien vu, merci.

L'ancienne source de données (plus à jour) est revenu, j'ai donc rollback à l'ancienne version (https://github.com/pgrimaud/ratp-api-rest/commit/f1e3684c767e79dc530d98a52265b4979c214859).

Tout devrait rentrer dans l'ordre.

Pierre
