### ISSUE TITLE
[Erreur 400] T3a 

### ISSUE THREAD

**Issue by tJulianB** [pgrimaud/horaires-ratp-api#88]
Hello, merci pour cette superbe API !
Depuis hier j'ai des petits soucis sur les T3a et T3b, parfois la même requête renvoie une erreur 400, parfois elle fonctionne...

_Exemple :_ 
https://api-ratp.pierre-grimaud.fr/v3/schedules/tramways/3a/porte+d'ivry/A+R donne tantôt
```
{
    "result": {
        "code": 400,
        "message": "Ambiguous Line"
    },
    "_metadata": {
        "call": "GET /schedules/tramways/3a/porte+d'ivry/A+R",
        "date": "2019-05-25T16:05:50+02:00",
        "version": 3
    }
}
``` 

... tantôt

```
{
    "result": {
        "schedules": [
            {
                "message": "2 mn",
                "destination": "Porte de Vincennes"
            },
            {
                "message": "9 mn",
                "destination": "Porte de Vincennes"
            },
            {
                "message": "A l'arret",
                "destination": "Pont Garigliano - Hopital Europeen George Pompidou"
            },
            {
                "message": "5 mn",
                "destination": "Pont Garigliano - Hopital Europeen George Pompidou"
            }
        ]
    },
    "_metadata": {
        "call": "GET /schedules/tramways/3a/porte+d'ivry/A+R",
        "date": "2019-05-25T16:08:35+02:00",
        "version": 3
    }
}
``` 

Le soucis arrive aussi sur le T3b et de nombreux bus (132 par exemple), mais cette fois Refresh ne change rien

Merci beaucoup !

**Comment by Cqoicebordel** [comment]
Je confirme, j'ai le même problème avec https://api-ratp.pierre-grimaud.fr/v3/schedules/bus/96/parmentier/R (ou /A)
```
{
    "result": {
        "code": 400,
        "message": "Ambiguous Line"
    },
    "_metadata": {
        "call": "GET /schedules/bus/96/parmentier/A",
        "date": "2019-05-25T18:12:40+02:00",
        "version": 3
    }
}
```

(et au passage, merci beaucoup pour cette API. Avant, je parsais le site wap, mais il est mort depuis longtemps... Bref, merci !)

**Comment by anup92k** [comment]
Je suis plutôt rassuré de voir cela.
Je découvre cet API depuis hier et je pensais que j'avais mal écris ma demande.
Pour moi c'est le GET suivant qui rate :
https://api-ratp.pierre-grimaud.fr/v3/schedules/tramways/6/velizy+2/A

Je ne pense pas m'être trompé sur les paramètres en vu des tests suivants (résultats tronqués) :

> curl  https://api-ratp.pierre-grimaud.fr/v3/lines

```
{
    "result": {
        "tramways": [
            {
                "code": "6",
                "name": "Tramway T6",
                "directions": "Viroflay - Rive Droite / Chatillon - Montrouge",
                "id": "322861"
            }
        ]
	}
}
```

> curl https://api-ratp.pierre-grimaud.fr/v3/stations/tramways/6

```
{
    "result": {
        "stations": [

            {
                "slug": "velizy+2",
                "name": "Velizy 2"
            },
        ]
    }
}
```
J'ai l'impression que le problème vient de la partie horaires de l'API (schedules) seulement.

**Comment by pgrimaud** [comment]
Bonjour,

Merci pour vos retours.

Je viens d'effectuer quelques tests, et je n'ai pas d'erreurs de mon côté. L'information provient de la RATP, et il se peut qu'une erreur soit présente de leur côté.

À savoir qu'un cache Redis est présent sur l'API. Donc si vous avez une erreur elle sera mise en cache pendant 30 secondes.

Je suis sur le point de finaliser une version 4 de l'API, qui devrait corriger ce problème via un second call sur l'API RATP SOAP (au cas où) en cas de retour "Ambiguous Line".

**Comment by anup92k** [comment]
Bonjour,

Effectivement cela fonctionne.
Merci pour votre retour et merci pour ce projet !

**Comment by tJulianB** [comment]
En effet tout est redevenu normal, merci beaucoup et vivement cette version 4 :)
