### ISSUE TITLE
Destination API only returns one destination for bus 72

### ISSUE THREAD

**Issue by ChadiEM** [pgrimaud/horaires-ratp-api#89]
Hello, after the bus reorg, I started having this issue of only one destination for bus 72.

`https://api-ratp.pierre-grimaud.fr/v3/destinations/bus/72?_format=json`

only returns 'Parc de Saint-Cloud', and not the other direction.

```
{
    "result": {
        "destinations": [
            {
                "name": "Parc de Saint-Cloud",
                "way": "A"
            }
        ]
    },
    "_metadata": {
        "call": "GET /destinations/bus/72",
        "date": "2019-04-22T10:00:49+02:00",
        "version": 3
    }
}
```

Others seem to be working fine (I don't have an exhaustive list of those that are not working).

**Comment by pgrimaud** [comment]
Hello, je viens de transférer cette issue côté documentation de mon API RATP pour tout centraliser.

Pour information, c'est corrigé sur la v4. 😄

Je clôturerai cette issue quand elle sera officiellement release.

Pierre

**Comment by pgrimaud** [comment]
https://api-ratp.pierre-grimaud.fr/v4/destinations/buses/72

**Comment by pgrimaud** [comment]
Hi @ChadiEM 

Fixed in API v4 : https://api-ratp.pierre-grimaud.fr/v4/destinations/buses/72

Regards

**Comment by ChadiEM** [comment]
Thanks! :-)
