### ISSUE TITLE
Adaptation à d'autres Réseaux de Transports en Commun ?

### ISSUE THREAD

**Issue by benoitdevries** [pgrimaud/horaires-ratp-api#91]
Bonjour,

tout d'abord merci pour ce module très pratique.
Est-il techniquement possible de l'adapter pour une autre ville ?
Quels pré-requis en terme de connaissance de langage faut-il ?

A bientôt !

**Comment by pgrimaud** [comment]
Hello @benoitdevries,

Oui c'est très largement adaptable pour n'importe quel ville.
Il faut quelques bases en PHP néanmoins. 

Quelle ville par exemple ?

**Comment by benoitdevries** [comment]
Bonjour Pierre,

Merci pour cette réponse. 
Je pense à Grenoble. 
La Tag et Itinisère fournissent leur API. 
Php, je suis un peu rouillé mais c devrait le faire. 

Benoît.
