### ISSUE TITLE
Invalid line code: 4

### ISSUE THREAD

**Issue by romainlouvet** [pgrimaud/horaires-ratp-api#92]
curl -X GET "https://api-ratp.pierre-grimaud.fr/v4/traffic/metros/4" -H "accept: application/json"

```
{
    "result": {
        "code": 400,
        "message": "Bad request. Invalid line code : 4"
    },
    "_metadata": {
        "call": "GET /traffic/metros/4",
        "date": "2019-10-04T13:16:37+02:00",
        "version": 4
    }
}

```
pourtant au get sur lines
```
{
        "code": "4",
        "name": "Métro 4",
        "directions": "Mairie de Montrouge / Porte de Clignancourt",
        "id": "70"
      }
```

**Comment by pgrimaud** [comment]
Bonjour,

La RATP a amélioré la protection de la page https://www.ratp.fr/meteo/ajax/data avec Cloudflare.
Je n'arrive pas à bypass cette sécurité...

Toute aide serait la bienvenue :
https://github.com/pgrimaud/ratp-api-rest/blob/master/src/Client/RatpWebsiteClient.php#L16
