### ISSUE TITLE
API down

### ISSUE THREAD

**Issue by a3nm** [pgrimaud/horaires-ratp-api#94]
Bonjour,

L'API semble down actuellement (pas de réponse du serveur), aussi d'après https://downforeveryoneorjustme.com/api-ratp.pierre-grimaud.fr

Merci beaucoup pour ce service !

**Comment by a3nm** [comment]
Il semble qu'elle soit revenue aujourd'hui. Mais hier, elle fonctionnait par intermittence.

**Comment by pgrimaud** [comment]
Hello,

Oui j'ai quelques soucis d'infra en ce moment. L'API est de plus en plus utilisée.
