### ISSUE TITLE
Le serveur met du temps pour répondre

### ISSUE THREAD

**Issue by TeamobDev** [pgrimaud/horaires-ratp-api#96]
Bonjour, 

J'ai constaté récemment une lenteur dans la réponse de tous les web services, parfois ça donne erreur, mais en général ça met énormément de temps pour afficher la réponse.
Après ça pourrait être normal, du à une surcharge sur le serveur.
Mais si vous arrivez à savoir pourquoi, et me faire un retour ça serait génial.
Mercii :)

**Comment by pgrimaud** [comment]
Hello, beaucoup d'appels simultanés (~150) sur un serveur avec de faibles ressources.
