### ISSUE TITLE
Stylisation du site

### ISSUE THREAD

**Issue by zkimi** [pgrimaud/horaires-ratp-api#99]
Hello!
Ce message n'est pas une demande pour un problème.
J'aime beaucoup ton projet et je l'ai adapté fidèlement aux vrais panneaux de la RATP!

Tu peux regarder je l'ai mis sur mon github!

Merci encore!

**Comment by pgrimaud** [comment]
Hello @zkimi 

Merci de ton retour, le panneau est très ressemblant. Bravo ! 👍
